/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef POWER_LIBPERFMGR_AUDIOSTREAMING_H_
#define POWER_LIBPERFMGR_AUDIOSTREAMING_H_
enum AUDIO_STREAMING_HINT
{
    AUDIO_STREAMING_OFF = 0,
    AUDIO_STREAMING_ON = 1,
    TPU_BOOST_OFF = 1000,
    TPU_BOOST_SHORT = 1001,
    TPU_BOOST_LONG = 1002
};
enum TPU_HINT_DURATION_MS
{
    SHORT = 200,
    LONG = 2000
};
#endif // POWER_LIBPERFMGR_AUDIOSTREAMING_H_
